Import('env')

libnssfix = env.SharedLibrary(
    target = 'nssfix',
    source = [
        'nssfix.c',
    ],

    LIBS = [
        # These aren't needed for the library itself, but for
        # staticx.hooks.glibc to discover their paths.
        'nss_files',
        'nss_dns',
    ],
)

Return('libnssfix')
