Import('env')

from staticx.bcjfilter import BCJFilter

# Enable the BCJ filter appropriate for this platform
bcj_filter = BCJFilter.for_current_arch()
if bcj_filter:
    env.Append(CPPDEFINES = {bcj_filter.xz_dec_macro: 1})

libxz = env.StaticLibrary(
    target = 'xz',
    source = [
        'xz_crc32.c',
        'xz_dec_lzma2.c',
        'xz_dec_stream.c',
        'xz_dec_bcj.c',
    ]
)

Return('libxz')
