env = Environment(
    BUILD_DIR = '#build',
    DIST_DIR = '#dist',
    LIB_DIR = '$DIST_DIR/lib',
    BIN_DIR = '$DIST_DIR/bin',

    # https://github.com/SCons/scons/wiki/UsingOrigin
    LINKFLAGS = ['-z', 'origin'],

    # Programs look for shared libs in ../lib
    PROG_RPATH = Literal('\\$$ORIGIN/../lib'),

    # Libraries look for shared libs in .
    LIB_RPATH = Literal('\\$$ORIGIN'),

    CCFLAGS = ['-Wall', '-Werror'],
    LIBPATH = ['$LIB_DIR'],
)

env.SConscript(
    'SConscript',
    variant_dir = '$BUILD_DIR',
    duplicate = False,
    exports = dict(env = env),
)
